### ISSUE TITLE
Pacbio header line name inconsistent

### ISSUE THREAD

**Issue by sjackman** [thegenemyers/DAZZ_DB#10]
I'm seeing this error message `Pacbio header line name inconsisten`. Can you help me determine what's wrong with this header? `fasta2DB` has no trouble with the lines before it in this file.

```
❯❯❯ fasta2DB pg29mt-scaffolds pg29mt-scaffolds.fasta Spruce_allC2_2k_84_filtered_subreads.fasta Spruce_allXL_2k_84_filtered_subreads.fasta
File Spruce_allC2_2k_84_filtered_subreads.fasta, Line 103835: Pacbio header line name inconsisten
```

Line 103835 is:
```
>m121122_033934_42160_c100417372550000001523039501151314_s1_p0/609/0_2866
```

DAZZ_DB version 1.0

**Comment by thegenemyers** [comment]
fasta2DB expects the data from a *single* SMRT cell in a given fasta.  
You must
have concatenated together data from several cells.  The DB wants to 
organize
and store data cell by cell.  It saves a lot of space to know that the 
header line is
all the same except for three numbers at the end.
    -- Gene

**Comment by sjackman** [comment]
Thanks for the clarification, Gene. I have no need to preserve the original read names. I'd be happy enough if they were distinguished by file name and the position of the read within that file. Perhaps you'd consider adding an option to `fasta2DB` that indicates it should ignore the FASTA header, and replace it with something useful to DAZZ_DB? That option would obviate the need for scripts like [nanocorrect-preprocess.pl](https://github.com/jts/nanocorrect/blob/master/nanocorrect-preprocess.pl#L17) that create fake PacBio headers.

**Comment by thegenemyers** [comment]
Sorry for the very long delay in responding to this -- I've been focused on trying to produce a scrubber that I can release to y'all.

I added a -p<string> option to fasta2DB that should take care of the issue and hence allow you to simplify your nanopore pipeline.  Basically the option says to ignore the prefix in the Pacbio headers and replace it with the string supplied with the -p option.  Each .fasta header must be a properly formatted Pacbio header, but the prefix string is otherwise ignored.  I just committed the new version 5 minutes ago after a little testing.

   Cheers,  Gene
