### ISSUE TITLE
fasta2DB does too much

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DAZZ_DB#18]
I would like to do something like this (using a feature of **bash** called *process substitution*):

    fasta2DB foo <(gunzip -c bar.fasta.gz)

**bash** creates a temporary *named pipe* called something like `/dev/fd/42` and streams the result of **gunzip**. That fails for 2 reasons:

1. **fasta2DB** requires a `.fasta` filename extension, and
1. **fasta2DB** requires a unique base filename for every fasta input.

I would rather use a much simpler **fasta2DB**, one which expects me to manage the filenames and their uniqueness myself. I don't even need to use a FileOfFileNames, or to provide a list of multiple fasta inputs. All of that is easy to script. I have to pre-process all fasta input anyway -- for PacBio headers and sequence line lengths. I would rather keep **fasta2DB* simple, to do just one thing as efficiently as possible. What do you think?

If you really want to index the inputs, this would be fine:

    gunzip -c bar.fasta.gz | fasta2DB -nbar foo

**Comment by thegenemyers** [comment]
I could do this, but it would destroy DB2fasta which exactly recreates 
the files that
were passed to fasta2DB.  The idea is that once you build the database, 
you don't
need to keep the .fasta's anymore, they are effectively redundant and 
you can throw
them away.  So instead of having .25n bytes in the data base and another 
n bytes in
.fasta files (or ~.33n bytes in a gzip of said), you can just keep the 
.25n bytes saving you
a lot of disk (n = the number of bases in the data set).

I typically convert all .bax.h5 files to .fasta's and .quiva's (the QV 
streams for Quiver),
load them into a DB with fasta2DB and quiva2DB, and then throw them 
away, and
push the .bax.h5 files to tape storage.  The .fasta and .quiva files can 
be recreated
from the DB with DB2fasta and DB2quiva.  All the information I'm ever 
gonna need
is in that DB and its all compressed.  This seems very clean to me. Why 
keep a gzip'd
version around when its already compressed in the DB?

Anyway, I can add the option, and you can do as you please, but bear in 
mind that the
inversion functions DB2fasta and DB2quiva will then symmetrically not 
recreate a set
of files but will recreate the ASCII .fasta and .quiva files to the 
standard output.

    -- Gene

**Comment by pb-cdunn** [comment]
First, yes, I understand the reasoning. I don't want to keep the .fasta or .fasta.gz files around either. But I *must* pre-process the original .fasta because:

1. **fasta2DB** cannot read arbitrarily long sequence lines. (It seems that a sequence can be arbitrarily long, but each line of fasta is restricted to 10kB.)
1. **fasta2DB** requires exactly 1 movie per input fasta.
1. **fasta2DB** requires PacBio-format headers. (I often hear complaints about this on GitHub.)

Since **fasta2DB** requires an actual file, these intermediate files must actually exist at some point. Many users are limited by the slowness of their filesystems, so it makes sense for the intermediate files to be compressed as they are created. You could make **fasta2DB** even more complicated by reading gzipped files automatically, but I don't want you to link **fasta2DB** with **zlib** because that would become an integration problem.

But that's not even the point. I am trying to dissuade you from making things complicated: Reduce the number of lines of code and increase flexibility.

I understand the goal to recreate the inputs. That's fine. But note that your current scheme already has a problem:

    fasta2DB foo /tmp/yesterday/craigventer.fasta
    fasta2DB foo /tmp/today/craigventer.fasta

That will fail because the file *basenames* match. Furthermore, your current scheme only recreates the files in the current directory, not in their original directories. That makes sense, but it's incorrect to claim that it precisely recreates the state of the world before input. It recreates only the *contents* of the inputs. So who cares about the exact filenames?

I'm saying that all you need is this:

    fasta2DB -nname dbname < name.fasta

**fasta2DB** can still require a unique `name`, and it can still use that to recreate all input files.

> [B]ear in mind that the inversion functions DB2fasta and DB2quiva will then symmetrically not recreate a set of files but will recreate the ASCII .fasta and .quiva files to the standard output.

I do not think those need to be altered at all.

**Comment by pb-cdunn** [comment]
On the other hand, writing the temporary intermediate files as `.gz` is not a huge win. Maybe 75GB instead of 300GB. It matters, but it's just one time.

Question: What is the relative cost of running **fasta2DB** N separate times for N files? I mean, in terms of disk access (i.e. loading the DB from disk and then saving), is adding a new file proportional only to the size of the new file, or to size of the database so far?

**Comment by thegenemyers** [comment]
Adding to a DB with fasta2DB takes time proportional to *only the new 
data added*
and to the size of the current .db stub file.  The latter is in order to 
read in all the names
of the previously input files in order to ensure a duplicate file is not 
read in.  This latter
bit is also almost negligible in time as one has typically several 
hundred SMRT cells in a project.
    -- Gene

**Comment by pb-cdunn** [comment]
I think you've resolved this with your recent changes.
