### ISSUE TITLE
Fastq support

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DAZZ_DB#30]
Hi,
Is fastq supported by fasta2DB? If not is there a way to reconstruct fastq files from fasta2DB?

Thank you in advance.

Michal

**Comment by thegenemyers** [comment]
No it is not.  The QV values produced by Pacbio are useless so I saw no reason to
support fastq.  Figured that if someone produced .fastq using the PB utilitiese, then
they could just convert .fastq to .fasta for the input.  But in general, you do want the
information for with Quiver or Arrow and this can only be obtained directly from the
.bax.h5 or .bam files.   However, perhaps I don't understand your use-case.

**Comment by thegenemyers** [comment]
I'm afraid not.  Quality values for Pacbio data are absolutely 
meaningless and
so producing a .fastq is a useless exercise, .fasta (and .arrow for the 
arrow data) is
all one needs/uses.
    -- Gene

**Comment by thegenemyers** [comment]
If the deeper issue is that you would like to attribute a QV score to 
every base for
the purposes of displaying a consensus in a conventional consensus 
viewer tool,
then the issue is a deep one as while the Pacbio guys do produce .fastq, 
as I said
there number are basically meaningless, or nearly so.  I would simply 
disable that
feature of your consensus viewer.
    -- Gene
